version: '3.3'
services:
  rubyap:
    tty: true
    stdin_open: true
    image: 'sakarsh/ruby-app-deployment-example-project:latest'
    networks:
      - rubyap-net
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
  nginx:
    image: nginx:stable
    networks:
      - rubyap-net
    ports:
      - '80:80'
    volumes:
      - '/var/log/nginx/rubyap'
      - '$PWD/rubyap.conf:/etc/nginx/conf.d/default.conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
    depends_on:
      - rubyap
networks:
  rubyap-net:
