apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-nodeport-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.container.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30038
