apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.container.name }}
  name: {{ .Values.container.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: {{ .Values.container.name }}
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/{{ .Values.container.name }}-default: "true"
        io.kompose.service: {{ .Values.container.name }}
    spec:
      containers:
        - image: sakarsh/{{ .Values.container.name }}:latest
          name: {{ .Values.container.name }}
          ports:
            - containerPort: {{ .Values.container.port }}
              hostPort: {{ .Values.container.port }}
              protocol: TCP
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
