apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Values.container.name }}
  name: {{ .Values.container.name }}
spec:
  ports:
    - name: "{{ .Values.container.port }}"
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    io.kompose.service: {{ .Values.container.name }}
status:
  loadBalancer: {}
