apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.container.name }}
  name: {{ .Values.container.name }}-service
spec:
  type: ClusterIP
  ports:
    - name: "{{ .Values.container.port }}"
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
status:
  loadBalancer: {}
