apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.container.name }}
  name: {{ .Values.container.name }}
spec:
  ports:
    - name: "{{ .Values.container.port }}"
      port: {{ .Values.container.port }}
      targetPort: {{ .Values.container.port }}
      nodePort: 3100
    type: loadBalancer
  selector:
    app: {{ .Values.container.name }}
status:
  loadBalancer: {}
