name: Lint on push

run-name: Lint on ${{ inputs.build_id }}

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ruby-app
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.159.0
        with:
          ruby-version: "3.2.2"
      - name: Run bundle install
        run: bundle install
      - name: Check Rubocop Styles
        run: rubocop
