name: Lint on push

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.159.0
        with:
          ruby-version: "3.2.2"
      - name: Change path to ruby-app
        run: |
          cd ruby-app
      - run: bundle install
      - name: Rubocop
        run: rubocop
