name: Unit test on push

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./ruby-app
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.159.0
        with:
          ruby-version: "3.2.2"
      - run: bundle install
      - name: Start the server in the background
        run: |
          sudo ruby http_server.rb &
          sleep 5
      - name: Unit test
        run: sudo ruby http_server_test.rb
